# Generated by Django 5.1.3 on 2024-12-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_approve_app', '0004_alter_loanpredictionmodel_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanpredictionmodel',
            old_name='ApprovedPercent',
            new_name='ApprovedPercentage',
        ),
        migrations.RenameField(
            model_name='loanpredictionmodel',
            old_name='Credit_History',
            new_name='CreditHistory',
        ),
        migrations.RenameField(
            model_name='loanpredictionmodel',
            old_name='Loan_Amount_Term',
            new_name='LoanAmountTerm',
        ),
        migrations.RenameField(
            model_name='loanpredictionmodel',
            old_name='RejectedPercent',
            new_name='RejectedPercentage',
        ),
    ]
